### ISSUE TITLE
CSRF vulnerability in resetall.php

### ISSUE THREAD

**Issue by mudrd8mz** [ponlawat-w/moodle-local_accessibility#7]
There is no sesskey protection in the resetall.php, and likely in other places the plugin. As a result I was able to put this HTML as a Moodle content (e.g. to a forum post or so):
```
<img src="/local/accessibility/resetall.php" alt="" width="1" height="1">
```

and it effectively resets the setting for any user looking at that page. This might be even more serious when it used the `returnurl` argument.

Please refer to https://moodledev.io/general/development/policies/security/crosssite-request-forgery

**Comment by ponlawat-w** [comment]
Hi @mudrd8mz, thank you for raising the issue. I will be working on this and patch a new version as soon as possible.
